CREATE TABLE mytable(
   artist_id INTEGER  NOT NULL PRIMARY KEY 
  ,name      VARCHAR(85) NOT NULL
);
INSERT INTO mytable(artist_id,name) VALUES (1,'AC/DC');
INSERT INTO mytable(artist_id,name) VALUES (2,'Accept');
INSERT INTO mytable(artist_id,name) VALUES (3,'Aerosmith');
INSERT INTO mytable(artist_id,name) VALUES (4,'Alanis Morissette');
INSERT INTO mytable(artist_id,name) VALUES (5,'Alice In Chains');
INSERT INTO mytable(artist_id,name) VALUES (6,'Antônio Carlos Jobim');
INSERT INTO mytable(artist_id,name) VALUES (7,'Apocalyptica');
INSERT INTO mytable(artist_id,name) VALUES (8,'Audioslave');
INSERT INTO mytable(artist_id,name) VALUES (9,'BackBeat');
INSERT INTO mytable(artist_id,name) VALUES (10,'Billy Cobham');
INSERT INTO mytable(artist_id,name) VALUES (11,'Black Label Society');
INSERT INTO mytable(artist_id,name) VALUES (12,'Black Sabbath');
INSERT INTO mytable(artist_id,name) VALUES (13,'Body Count');
INSERT INTO mytable(artist_id,name) VALUES (14,'Bruce Dickinson');
INSERT INTO mytable(artist_id,name) VALUES (15,'Buddy Guy');
INSERT INTO mytable(artist_id,name) VALUES (16,'Caetano Veloso');
INSERT INTO mytable(artist_id,name) VALUES (17,'Chico Buarque');
INSERT INTO mytable(artist_id,name) VALUES (18,'Chico Science & Nação Zumbi');
INSERT INTO mytable(artist_id,name) VALUES (19,'Cidade Negra');
INSERT INTO mytable(artist_id,name) VALUES (20,'Cláudio Zoli');
INSERT INTO mytable(artist_id,name) VALUES (21,'Various Artists');
INSERT INTO mytable(artist_id,name) VALUES (22,'Led Zeppelin');
INSERT INTO mytable(artist_id,name) VALUES (23,'Frank Zappa & Captain Beefheart');
INSERT INTO mytable(artist_id,name) VALUES (24,'Marcos Valle');
INSERT INTO mytable(artist_id,name) VALUES (25,'Milton Nascimento & Bebeto');
INSERT INTO mytable(artist_id,name) VALUES (26,'Azymuth');
INSERT INTO mytable(artist_id,name) VALUES (27,'Gilberto Gil');
INSERT INTO mytable(artist_id,name) VALUES (28,'João Gilberto');
INSERT INTO mytable(artist_id,name) VALUES (29,'Bebel Gilberto');
INSERT INTO mytable(artist_id,name) VALUES (30,'Jorge Vercilo');
INSERT INTO mytable(artist_id,name) VALUES (31,'Baby Consuelo');
INSERT INTO mytable(artist_id,name) VALUES (32,'Ney Matogrosso');
INSERT INTO mytable(artist_id,name) VALUES (33,'Luiz Melodia');
INSERT INTO mytable(artist_id,name) VALUES (34,'Nando Reis');
INSERT INTO mytable(artist_id,name) VALUES (35,'Pedro Luís & A Parede');
INSERT INTO mytable(artist_id,name) VALUES (36,'O Rappa');
INSERT INTO mytable(artist_id,name) VALUES (37,'Ed Motta');
INSERT INTO mytable(artist_id,name) VALUES (38,'Banda Black Rio');
INSERT INTO mytable(artist_id,name) VALUES (39,'Fernanda Porto');
INSERT INTO mytable(artist_id,name) VALUES (40,'Os Cariocas');
INSERT INTO mytable(artist_id,name) VALUES (41,'Elis Regina');
INSERT INTO mytable(artist_id,name) VALUES (42,'Milton Nascimento');
INSERT INTO mytable(artist_id,name) VALUES (43,'A Cor Do Som');
INSERT INTO mytable(artist_id,name) VALUES (44,'Kid Abelha');
INSERT INTO mytable(artist_id,name) VALUES (45,'Sandra De Sá');
INSERT INTO mytable(artist_id,name) VALUES (46,'Jorge Ben');
INSERT INTO mytable(artist_id,name) VALUES (47,'Hermeto Pascoal');
INSERT INTO mytable(artist_id,name) VALUES (48,'Barão Vermelho');
INSERT INTO mytable(artist_id,name) VALUES (49,'Edson, DJ Marky & DJ Patife Featuring Fernanda Porto');
INSERT INTO mytable(artist_id,name) VALUES (50,'Metallica');
INSERT INTO mytable(artist_id,name) VALUES (51,'Queen');
INSERT INTO mytable(artist_id,name) VALUES (52,'Kiss');
INSERT INTO mytable(artist_id,name) VALUES (53,'Spyro Gyra');
INSERT INTO mytable(artist_id,name) VALUES (54,'Green Day');
INSERT INTO mytable(artist_id,name) VALUES (55,'David Coverdale');
INSERT INTO mytable(artist_id,name) VALUES (56,'Gonzaguinha');
INSERT INTO mytable(artist_id,name) VALUES (57,'Os Mutantes');
INSERT INTO mytable(artist_id,name) VALUES (58,'Deep Purple');
INSERT INTO mytable(artist_id,name) VALUES (59,'Santana');
INSERT INTO mytable(artist_id,name) VALUES (60,'Santana Feat. Dave Matthews');
INSERT INTO mytable(artist_id,name) VALUES (61,'Santana Feat. Everlast');
INSERT INTO mytable(artist_id,name) VALUES (62,'Santana Feat. Rob Thomas');
INSERT INTO mytable(artist_id,name) VALUES (63,'Santana Feat. Lauryn Hill & Cee-Lo');
INSERT INTO mytable(artist_id,name) VALUES (64,'Santana Feat. The Project G&B');
INSERT INTO mytable(artist_id,name) VALUES (65,'Santana Feat. Maná');
INSERT INTO mytable(artist_id,name) VALUES (66,'Santana Feat. Eagle-Eye Cherry');
INSERT INTO mytable(artist_id,name) VALUES (67,'Santana Feat. Eric Clapton');
INSERT INTO mytable(artist_id,name) VALUES (68,'Miles Davis');
INSERT INTO mytable(artist_id,name) VALUES (69,'Gene Krupa');
INSERT INTO mytable(artist_id,name) VALUES (70,'Toquinho & Vinícius');
INSERT INTO mytable(artist_id,name) VALUES (71,'Vinícius De Moraes & Baden Powell');
INSERT INTO mytable(artist_id,name) VALUES (72,'Vinícius De Moraes');
INSERT INTO mytable(artist_id,name) VALUES (73,'Vinícius E Qurteto Em Cy');
INSERT INTO mytable(artist_id,name) VALUES (74,'Vinícius E Odette Lara');
INSERT INTO mytable(artist_id,name) VALUES (75,'Vinicius, Toquinho & Quarteto Em Cy');
INSERT INTO mytable(artist_id,name) VALUES (76,'Creedence Clearwater Revival');
INSERT INTO mytable(artist_id,name) VALUES (77,'Cássia Eller');
INSERT INTO mytable(artist_id,name) VALUES (78,'Def Leppard');
INSERT INTO mytable(artist_id,name) VALUES (79,'Dennis Chambers');
INSERT INTO mytable(artist_id,name) VALUES (80,'Djavan');
INSERT INTO mytable(artist_id,name) VALUES (81,'Eric Clapton');
INSERT INTO mytable(artist_id,name) VALUES (82,'Faith No More');
INSERT INTO mytable(artist_id,name) VALUES (83,'Falamansa');
INSERT INTO mytable(artist_id,name) VALUES (84,'Foo Fighters');
INSERT INTO mytable(artist_id,name) VALUES (85,'Frank Sinatra');
INSERT INTO mytable(artist_id,name) VALUES (86,'Funk Como Le Gusta');
INSERT INTO mytable(artist_id,name) VALUES (87,'Godsmack');
INSERT INTO mytable(artist_id,name) VALUES (88,'Guns N'' Roses');
INSERT INTO mytable(artist_id,name) VALUES (89,'Incognito');
INSERT INTO mytable(artist_id,name) VALUES (90,'Iron Maiden');
INSERT INTO mytable(artist_id,name) VALUES (91,'James Brown');
INSERT INTO mytable(artist_id,name) VALUES (92,'Jamiroquai');
INSERT INTO mytable(artist_id,name) VALUES (93,'JET');
INSERT INTO mytable(artist_id,name) VALUES (94,'Jimi Hendrix');
INSERT INTO mytable(artist_id,name) VALUES (95,'Joe Satriani');
INSERT INTO mytable(artist_id,name) VALUES (96,'Jota Quest');
INSERT INTO mytable(artist_id,name) VALUES (97,'João Suplicy');
INSERT INTO mytable(artist_id,name) VALUES (98,'Judas Priest');
INSERT INTO mytable(artist_id,name) VALUES (99,'Legião Urbana');
INSERT INTO mytable(artist_id,name) VALUES (100,'Lenny Kravitz');
INSERT INTO mytable(artist_id,name) VALUES (101,'Lulu Santos');
INSERT INTO mytable(artist_id,name) VALUES (102,'Marillion');
INSERT INTO mytable(artist_id,name) VALUES (103,'Marisa Monte');
INSERT INTO mytable(artist_id,name) VALUES (104,'Marvin Gaye');
INSERT INTO mytable(artist_id,name) VALUES (105,'Men At Work');
INSERT INTO mytable(artist_id,name) VALUES (106,'Motörhead');
INSERT INTO mytable(artist_id,name) VALUES (107,'Motörhead & Girlschool');
INSERT INTO mytable(artist_id,name) VALUES (108,'Mônica Marianno');
INSERT INTO mytable(artist_id,name) VALUES (109,'Mötley Crüe');
INSERT INTO mytable(artist_id,name) VALUES (110,'Nirvana');
INSERT INTO mytable(artist_id,name) VALUES (111,'O Terço');
INSERT INTO mytable(artist_id,name) VALUES (112,'Olodum');
INSERT INTO mytable(artist_id,name) VALUES (113,'Os Paralamas Do Sucesso');
INSERT INTO mytable(artist_id,name) VALUES (114,'Ozzy Osbourne');
INSERT INTO mytable(artist_id,name) VALUES (115,'Page & Plant');
INSERT INTO mytable(artist_id,name) VALUES (116,'Passengers');
INSERT INTO mytable(artist_id,name) VALUES (117,'Paul D''Ianno');
INSERT INTO mytable(artist_id,name) VALUES (118,'Pearl Jam');
INSERT INTO mytable(artist_id,name) VALUES (119,'Peter Tosh');
INSERT INTO mytable(artist_id,name) VALUES (120,'Pink Floyd');
INSERT INTO mytable(artist_id,name) VALUES (121,'Planet Hemp');
INSERT INTO mytable(artist_id,name) VALUES (122,'R.E.M. Feat. Kate Pearson');
INSERT INTO mytable(artist_id,name) VALUES (123,'R.E.M. Feat. KRS-One');
INSERT INTO mytable(artist_id,name) VALUES (124,'R.E.M.');
INSERT INTO mytable(artist_id,name) VALUES (125,'Raimundos');
INSERT INTO mytable(artist_id,name) VALUES (126,'Raul Seixas');
INSERT INTO mytable(artist_id,name) VALUES (127,'Red Hot Chili Peppers');
INSERT INTO mytable(artist_id,name) VALUES (128,'Rush');
INSERT INTO mytable(artist_id,name) VALUES (129,'Simply Red');
INSERT INTO mytable(artist_id,name) VALUES (130,'Skank');
INSERT INTO mytable(artist_id,name) VALUES (131,'Smashing Pumpkins');
INSERT INTO mytable(artist_id,name) VALUES (132,'Soundgarden');
INSERT INTO mytable(artist_id,name) VALUES (133,'Stevie Ray Vaughan & Double Trouble');
INSERT INTO mytable(artist_id,name) VALUES (134,'Stone Temple Pilots');
INSERT INTO mytable(artist_id,name) VALUES (135,'System Of A Down');
INSERT INTO mytable(artist_id,name) VALUES (136,'Terry Bozzio, Tony Levin & Steve Stevens');
INSERT INTO mytable(artist_id,name) VALUES (137,'The Black Crowes');
INSERT INTO mytable(artist_id,name) VALUES (138,'The Clash');
INSERT INTO mytable(artist_id,name) VALUES (139,'The Cult');
INSERT INTO mytable(artist_id,name) VALUES (140,'The Doors');
INSERT INTO mytable(artist_id,name) VALUES (141,'The Police');
INSERT INTO mytable(artist_id,name) VALUES (142,'The Rolling Stones');
INSERT INTO mytable(artist_id,name) VALUES (143,'The Tea Party');
INSERT INTO mytable(artist_id,name) VALUES (144,'The Who');
INSERT INTO mytable(artist_id,name) VALUES (145,'Tim Maia');
INSERT INTO mytable(artist_id,name) VALUES (146,'Titãs');
INSERT INTO mytable(artist_id,name) VALUES (147,'Battlestar Galactica');
INSERT INTO mytable(artist_id,name) VALUES (148,'Heroes');
INSERT INTO mytable(artist_id,name) VALUES (149,'Lost');
INSERT INTO mytable(artist_id,name) VALUES (150,'U2');
INSERT INTO mytable(artist_id,name) VALUES (151,'UB40');
INSERT INTO mytable(artist_id,name) VALUES (152,'Van Halen');
INSERT INTO mytable(artist_id,name) VALUES (153,'Velvet Revolver');
INSERT INTO mytable(artist_id,name) VALUES (154,'Whitesnake');
INSERT INTO mytable(artist_id,name) VALUES (155,'Zeca Pagodinho');
INSERT INTO mytable(artist_id,name) VALUES (156,'The Office');
INSERT INTO mytable(artist_id,name) VALUES (157,'Dread Zeppelin');
INSERT INTO mytable(artist_id,name) VALUES (158,'Battlestar Galactica (Classic)');
INSERT INTO mytable(artist_id,name) VALUES (159,'Aquaman');
INSERT INTO mytable(artist_id,name) VALUES (160,'Christina Aguilera featuring BigElf');
INSERT INTO mytable(artist_id,name) VALUES (161,'Aerosmith & Sierra Leone''s Refugee Allstars');
INSERT INTO mytable(artist_id,name) VALUES (162,'Los Lonely Boys');
INSERT INTO mytable(artist_id,name) VALUES (163,'Corinne Bailey Rae');
INSERT INTO mytable(artist_id,name) VALUES (164,'Dhani Harrison & Jakob Dylan');
INSERT INTO mytable(artist_id,name) VALUES (165,'Jackson Browne');
INSERT INTO mytable(artist_id,name) VALUES (166,'Avril Lavigne');
INSERT INTO mytable(artist_id,name) VALUES (167,'Big & Rich');
INSERT INTO mytable(artist_id,name) VALUES (168,'Youssou N''Dour');
INSERT INTO mytable(artist_id,name) VALUES (169,'Black Eyed Peas');
INSERT INTO mytable(artist_id,name) VALUES (170,'Jack Johnson');
INSERT INTO mytable(artist_id,name) VALUES (171,'Ben Harper');
INSERT INTO mytable(artist_id,name) VALUES (172,'Snow Patrol');
INSERT INTO mytable(artist_id,name) VALUES (173,'Matisyahu');
INSERT INTO mytable(artist_id,name) VALUES (174,'The Postal Service');
INSERT INTO mytable(artist_id,name) VALUES (175,'Jaguares');
INSERT INTO mytable(artist_id,name) VALUES (176,'The Flaming Lips');
INSERT INTO mytable(artist_id,name) VALUES (177,'Jack''s Mannequin & Mick Fleetwood');
INSERT INTO mytable(artist_id,name) VALUES (178,'Regina Spektor');
INSERT INTO mytable(artist_id,name) VALUES (179,'Scorpions');
INSERT INTO mytable(artist_id,name) VALUES (180,'House Of Pain');
INSERT INTO mytable(artist_id,name) VALUES (181,'Xis');
INSERT INTO mytable(artist_id,name) VALUES (182,'Nega Gizza');
INSERT INTO mytable(artist_id,name) VALUES (183,'Gustavo & Andres Veiga & Salazar');
INSERT INTO mytable(artist_id,name) VALUES (184,'Rodox');
INSERT INTO mytable(artist_id,name) VALUES (185,'Charlie Brown Jr.');
INSERT INTO mytable(artist_id,name) VALUES (186,'Pedro Luís E A Parede');
INSERT INTO mytable(artist_id,name) VALUES (187,'Los Hermanos');
INSERT INTO mytable(artist_id,name) VALUES (188,'Mundo Livre S/A');
INSERT INTO mytable(artist_id,name) VALUES (189,'Otto');
INSERT INTO mytable(artist_id,name) VALUES (190,'Instituto');
INSERT INTO mytable(artist_id,name) VALUES (191,'Nação Zumbi');
INSERT INTO mytable(artist_id,name) VALUES (192,'DJ Dolores & Orchestra Santa Massa');
INSERT INTO mytable(artist_id,name) VALUES (193,'Seu Jorge');
INSERT INTO mytable(artist_id,name) VALUES (194,'Sabotage E Instituto');
INSERT INTO mytable(artist_id,name) VALUES (195,'Stereo Maracana');
INSERT INTO mytable(artist_id,name) VALUES (196,'Cake');
INSERT INTO mytable(artist_id,name) VALUES (197,'Aisha Duo');
INSERT INTO mytable(artist_id,name) VALUES (198,'Habib Koité and Bamada');
INSERT INTO mytable(artist_id,name) VALUES (199,'Karsh Kale');
INSERT INTO mytable(artist_id,name) VALUES (200,'The Posies');
INSERT INTO mytable(artist_id,name) VALUES (201,'Luciana Souza/Romero Lubambo');
INSERT INTO mytable(artist_id,name) VALUES (202,'Aaron Goldberg');
INSERT INTO mytable(artist_id,name) VALUES (203,'Nicolaus Esterhazy Sinfonia');
INSERT INTO mytable(artist_id,name) VALUES (204,'Temple of the Dog');
INSERT INTO mytable(artist_id,name) VALUES (205,'Chris Cornell');
INSERT INTO mytable(artist_id,name) VALUES (206,'Alberto Turco & Nova Schola Gregoriana');
INSERT INTO mytable(artist_id,name) VALUES (207,'Richard Marlow & The Choir of Trinity College, Cambridge');
INSERT INTO mytable(artist_id,name) VALUES (208,'English Concert & Trevor Pinnock');
INSERT INTO mytable(artist_id,name) VALUES (209,'Anne-Sophie Mutter, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO mytable(artist_id,name) VALUES (210,'Hilary Hahn, Jeffrey Kahane, Los Angeles Chamber Orchestra & Margaret Batjer');
INSERT INTO mytable(artist_id,name) VALUES (211,'Wilhelm Kempff');
INSERT INTO mytable(artist_id,name) VALUES (212,'Yo-Yo Ma');
INSERT INTO mytable(artist_id,name) VALUES (213,'Scholars Baroque Ensemble');
INSERT INTO mytable(artist_id,name) VALUES (214,'Academy of St. Martin in the Fields & Sir Neville Marriner');
INSERT INTO mytable(artist_id,name) VALUES (215,'Academy of St. Martin in the Fields Chamber Ensemble & Sir Neville Marriner');
INSERT INTO mytable(artist_id,name) VALUES (216,'Berliner Philharmoniker, Claudio Abbado & Sabine Meyer');
INSERT INTO mytable(artist_id,name) VALUES (217,'Royal Philharmonic Orchestra & Sir Thomas Beecham');
INSERT INTO mytable(artist_id,name) VALUES (218,'Orchestre Révolutionnaire et Romantique & John Eliot Gardiner');
INSERT INTO mytable(artist_id,name) VALUES (219,'Britten Sinfonia, Ivor Bolton & Lesley Garrett');
INSERT INTO mytable(artist_id,name) VALUES (220,'Chicago Symphony Chorus, Chicago Symphony Orchestra & Sir Georg Solti');
INSERT INTO mytable(artist_id,name) VALUES (221,'Sir Georg Solti & Wiener Philharmoniker');
INSERT INTO mytable(artist_id,name) VALUES (222,'Academy of St. Martin in the Fields, John Birch, Sir Neville Marriner & Sylvia McNair');
INSERT INTO mytable(artist_id,name) VALUES (223,'London Symphony Orchestra & Sir Charles Mackerras');
INSERT INTO mytable(artist_id,name) VALUES (224,'Barry Wordsworth & BBC Concert Orchestra');
INSERT INTO mytable(artist_id,name) VALUES (225,'Herbert Von Karajan, Mirella Freni & Wiener Philharmoniker');
INSERT INTO mytable(artist_id,name) VALUES (226,'Eugene Ormandy');
INSERT INTO mytable(artist_id,name) VALUES (227,'Luciano Pavarotti');
INSERT INTO mytable(artist_id,name) VALUES (228,'Leonard Bernstein & New York Philharmonic');
INSERT INTO mytable(artist_id,name) VALUES (229,'Boston Symphony Orchestra & Seiji Ozawa');
INSERT INTO mytable(artist_id,name) VALUES (230,'Aaron Copland & London Symphony Orchestra');
INSERT INTO mytable(artist_id,name) VALUES (231,'Ton Koopman');
INSERT INTO mytable(artist_id,name) VALUES (232,'Sergei Prokofiev & Yuri Temirkanov');
INSERT INTO mytable(artist_id,name) VALUES (233,'Chicago Symphony Orchestra & Fritz Reiner');
INSERT INTO mytable(artist_id,name) VALUES (234,'Orchestra of The Age of Enlightenment');
INSERT INTO mytable(artist_id,name) VALUES (235,'Emanuel Ax, Eugene Ormandy & Philadelphia Orchestra');
INSERT INTO mytable(artist_id,name) VALUES (236,'James Levine');
INSERT INTO mytable(artist_id,name) VALUES (237,'Berliner Philharmoniker & Hans Rosbaud');
INSERT INTO mytable(artist_id,name) VALUES (238,'Maurizio Pollini');
INSERT INTO mytable(artist_id,name) VALUES (239,'Academy of St. Martin in the Fields, Sir Neville Marriner & William Bennett');
INSERT INTO mytable(artist_id,name) VALUES (240,'Gustav Mahler');
INSERT INTO mytable(artist_id,name) VALUES (241,'Felix Schmidt, London Symphony Orchestra & Rafael Frühbeck de Burgos');
INSERT INTO mytable(artist_id,name) VALUES (242,'Edo de Waart & San Francisco Symphony');
INSERT INTO mytable(artist_id,name) VALUES (243,'Antal Doráti & London Symphony Orchestra');
INSERT INTO mytable(artist_id,name) VALUES (244,'Choir Of Westminster Abbey & Simon Preston');
INSERT INTO mytable(artist_id,name) VALUES (245,'Michael Tilson Thomas & San Francisco Symphony');
INSERT INTO mytable(artist_id,name) VALUES (246,'Chor der Wiener Staatsoper, Herbert Von Karajan & Wiener Philharmoniker');
INSERT INTO mytable(artist_id,name) VALUES (247,'The King''s Singers');
INSERT INTO mytable(artist_id,name) VALUES (248,'Berliner Philharmoniker & Herbert Von Karajan');
INSERT INTO mytable(artist_id,name) VALUES (249,'Sir Georg Solti, Sumi Jo & Wiener Philharmoniker');
INSERT INTO mytable(artist_id,name) VALUES (250,'Christopher O''Riley');
INSERT INTO mytable(artist_id,name) VALUES (251,'Fretwork');
INSERT INTO mytable(artist_id,name) VALUES (252,'Amy Winehouse');
INSERT INTO mytable(artist_id,name) VALUES (253,'Calexico');
INSERT INTO mytable(artist_id,name) VALUES (254,'Otto Klemperer & Philharmonia Orchestra');
INSERT INTO mytable(artist_id,name) VALUES (255,'Yehudi Menuhin');
INSERT INTO mytable(artist_id,name) VALUES (256,'Philharmonia Orchestra & Sir Neville Marriner');
INSERT INTO mytable(artist_id,name) VALUES (257,'Academy of St. Martin in the Fields, Sir Neville Marriner & Thurston Dart');
INSERT INTO mytable(artist_id,name) VALUES (258,'Les Arts Florissants & William Christie');
INSERT INTO mytable(artist_id,name) VALUES (259,'The 12 Cellists of The Berlin Philharmonic');
INSERT INTO mytable(artist_id,name) VALUES (260,'Adrian Leaper & Doreen de Feis');
INSERT INTO mytable(artist_id,name) VALUES (261,'Roger Norrington, London Classical Players');
INSERT INTO mytable(artist_id,name) VALUES (262,'Charles Dutoit & L''Orchestre Symphonique de Montréal');
INSERT INTO mytable(artist_id,name) VALUES (263,'Equale Brass Ensemble, John Eliot Gardiner & Munich Monteverdi Orchestra and Choir');
INSERT INTO mytable(artist_id,name) VALUES (264,'Kent Nagano and Orchestre de l''Opéra de Lyon');
INSERT INTO mytable(artist_id,name) VALUES (265,'Julian Bream');
INSERT INTO mytable(artist_id,name) VALUES (266,'Martin Roscoe');
INSERT INTO mytable(artist_id,name) VALUES (267,'Göteborgs Symfoniker & Neeme Järvi');
INSERT INTO mytable(artist_id,name) VALUES (268,'Itzhak Perlman');
INSERT INTO mytable(artist_id,name) VALUES (269,'Michele Campanella');
INSERT INTO mytable(artist_id,name) VALUES (270,'Gerald Moore');
INSERT INTO mytable(artist_id,name) VALUES (271,'Mela Tenenbaum, Pro Musica Prague & Richard Kapp');
INSERT INTO mytable(artist_id,name) VALUES (272,'Emerson String Quartet');
INSERT INTO mytable(artist_id,name) VALUES (273,'C. Monteverdi, Nigel Rogers - Chiaroscuro; London Baroque; London Cornett & Sackbu');
INSERT INTO mytable(artist_id,name) VALUES (274,'Nash Ensemble');
INSERT INTO mytable(artist_id,name) VALUES (275,'Philip Glass Ensemble');
